<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'AbstractAndoidLintEngine' => 'lint/engine/AndroidLintEngine.php',
    'AbstractArcanistAndroidLinter' => 'lint/linter/ArcanistAndroidLinter.php',
    'AndroidFullLintEngine' => 'lint/engine/AndroidLintEngine.php',
    'AndroidLintEngine' => 'lint/engine/AndroidLintEngine.php',
    'ArcanistAndroidFullLinter' => 'lint/linter/ArcanistAndroidLinter.php',
    'ArcanistAndroidLinter' => 'lint/linter/ArcanistAndroidLinter.php',
    'ArcanistAndroidLinterTestCase' => 'lint/linter/__tests__/ArcanistAndroidLinterTestCase.php',
    'ArcanistCustomLicenseLinter' => 'lint/linter/ArcanistCustomLicenseLinter.php',
    'ArcanistMobileGeneratedLinter' => 'lint/linter/ArcanistMobileGeneratedLinter.php',
    'ArcanistMobileGeneratedLinterTestCase' => 'lint/linter/__tests__/ArcanistMobileGeneratedLinterTestCase.php',
    'ArcanistOCFilenameLinter' => 'lint/linter/ArcanistOCFilenameLinter.php',
    'ArcanistOCLinter' => 'lint/linter/ArcanistOCLinter.php',
    'ArcanistOCLinterTestCase' => 'lint/linter/__tests__/ArcanistOCLinterTestCase.php',
    'ArcanistOCProjectLinter' => 'lint/linter/ArcanistOCProjectLinter.php',
    'ArcanistOCStaticAnalysisLinter' => 'lint/linter/ArcanistOCStaticAnalysisLinter.php',
    'ArcanistReSharperLinter' => 'lint/linter/ArcanistReSharperLinter.php',
    'BasicObjectiveCLintEngine' => 'lint/engine/BasicObjectiveCLintEngine.php',
    'MobileLintEngine' => 'lint/engine/MobileLintEngine.php',
    'MobileUnitTestEngine' => 'unit/MobileUnitTestEngine.php',
    'OCUnitTestEngine' => 'unit/OCUnitTestEngine.php',
  ),
  'function' => array(),
  'xmap' => array(
    'AbstractAndoidLintEngine' => 'ArcanistLintEngine',
    'AbstractArcanistAndroidLinter' => 'ArcanistLinter',
    'AndroidFullLintEngine' => 'AbstractAndoidLintEngine',
    'AndroidLintEngine' => 'AbstractAndoidLintEngine',
    'ArcanistAndroidFullLinter' => 'AbstractArcanistAndroidLinter',
    'ArcanistAndroidLinter' => 'AbstractArcanistAndroidLinter',
    'ArcanistAndroidLinterTestCase' => 'ArcanistLinterTestCase',
    'ArcanistCustomLicenseLinter' => 'ArcanistLinter',
    'ArcanistMobileGeneratedLinter' => 'ArcanistLinter',
    'ArcanistMobileGeneratedLinterTestCase' => 'ArcanistLinterTestCase',
    'ArcanistOCFilenameLinter' => 'ArcanistLinter',
    'ArcanistOCLinter' => 'ArcanistLinter',
    'ArcanistOCLinterTestCase' => 'ArcanistLinterTestCase',
    'ArcanistOCProjectLinter' => 'ArcanistLinter',
    'ArcanistOCStaticAnalysisLinter' => 'ArcanistLinter',
    'ArcanistReSharperLinter' => 'ArcanistLinter',
    'BasicObjectiveCLintEngine' => 'ArcanistLintEngine',
    'MobileLintEngine' => 'ArcanistLintEngine',
    'MobileUnitTestEngine' => 'ArcanistUnitTestEngine',
    'OCUnitTestEngine' => 'ArcanistUnitTestEngine',
  ),
));
